"""created tables

Revision ID: 9910570a70c3
Revises: 1fbfa43fdc29
Create Date: 2023-10-10 14:16:31.438558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9910570a70c3'
down_revision = '1fbfa43fdc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
